Adicionando RF/02
disciplinas-prof-Edeilson-UFT/eng-soft-2022-2 pull request #12
Opened 2022-09-24 23:46 UTC by pixies0

Realizado toda o caso de uso expandido e user stories do Requisito Funcional 02 - Cadastrar Usuário

Favor verificar se:

- [ ] As especificações satisfaz e descreve o requsito em questão.
- [ ] Se o documento está dentro da formalidade adotada.

2022-09-24 23:51 UTC, fernandokozak requested changes
atualizar documento fazendo favor

2022-09-24 23:51 UTC, fernandokozak commented on Relatório Especificação de Requisitos.md
> +- **Relatório do Usuário:**
favor fazer um relatorio de usuario

2022-09-24 23:58 UTC, pixies0 commented
@fernandokozak Fiz a alteração q vossa excelencia pediu ! Verifica ai jhow....

2022-09-25 00:00 UTC, fernandokozak commented
Agora ta bala meu primo, vou aprovar

2022-09-25 00:14 UTC, merged